# Generated by Django 4.0.5 on 2022-06-15 00:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Produtos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('vendedor', models.CharField(max_length=255)),
                ('valor', models.CharField(max_length=20)),
                ('imagem', models.CharField(max_length=200)),
            ],
        ),
    ]
