# Generated by Django 4.0.5 on 2022-06-15 02:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0002_remove_produtos_imagem'),
    ]

    operations = [
        migrations.AddField(
            model_name='produtos',
            name='imagem',
            field=models.ImageField(null=True, upload_to='produtos/'),
        ),
    ]
