# Generated by Django 4.0.5 on 2022-06-12 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vendedores',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('documento', models.CharField(max_length=18)),
                ('endereco', models.CharField(max_length=255)),
                ('telefone', models.CharField(max_length=12)),
                ('banco', models.CharField(max_length=50)),
                ('conta', models.CharField(max_length=10)),
                ('email', models.CharField(max_length=100)),
                ('senha', models.CharField(max_length=25)),
            ],
        ),
    ]
